name: unit-and-instrumented-tests
on: [push]
jobs:
  test:
    runs-on: macos-latest
    env:
      ANDROID_SDK_TOOLS:    "4333796"
      ANDROID_CMAKE:        "3.10.2.4988404"
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup java  
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Install Android sdkmanager
        run: |
          wget --quiet --output-document=android-sdk.zip https://dl.google.com/android/repository/sdk-tools-linux-${ANDROID_SDK_TOOLS}.zip
          sudo unzip -d $ANDROID_HOME android-sdk.zip > /dev/null
      - name: Install required Android tools
        run: |
          echo "y" | sudo $ANDROID_HOME/tools/bin/sdkmanager "cmake;${ANDROID_CMAKE}" > /dev/null
          echo "y" | sudo $ANDROID_HOME/tools/bin/sdkmanager --licenses > /dev/null
      - name: Build with Gradle
        run: |
          export PATH="$ANDROID_HOME/cmake/${ANDROID_CMAKE}/bin:$PATH"
          ./gradlew build
