name: unit-and-instrumented-tests
on: [push]
jobs:
  test:
    runs-on: macos-latest
    env:
      ANDROID_SDK_TOOLS:    "4333796"
      ANDROID_CMAKE:        "3.10.2.4988404"
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup java  
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Build with Gradle
        run: |
          export JAVA_HOME=`/usr/libexec/java_home -v 1.8`
          sdkmanager --install  "system-images;android-32;google_apis_playstore;x86_64"
          echo "no" | avdmanager create avd -f -n test -k "system-images;android-32;google_apis;x86_64"
          emulator -avd test & adb wait-for-device
          export JAVA_HOME=`/usr/libexec/java_home -v 11`
          ./gradlew connectedCheck --info