name: unit-and-instrumented-tests
on: [push]
jobs:
  test:
    runs-on: macos-latest
    strategy:
      matrix:
        api-level: [28]
        target: [google_apis]
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup java  
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
    - name: Setup gradle
      uses: gradle/gradle-build-action@v2    
    - name: Create Android emulator
      run: |
        sdkmanager --install "system-images;android-31;google_apis;x86_64"
        echo "no" | avdmanager --verbose create avd --force --name testAVD --abi google_apis/x86_64 --package 'system-images;android-31;google_apis;x86_64'
        
    - name: Copy jar files to app folder
      run: gradle extractLibs

    - name: Launch Emulator
      run: | 
        $ANDROID_SDK_ROOT/emulator/emulator -avd testAVD

    - name: Run instrumentation tests
      run: |                
        gradle connectedAndroidTest --info