name: unit-and-instrumented-tests
on: [push]
jobs:
  test:
    runs-on: macos-latest
    env:
      ANDROID_SDK_TOOLS:    "4333796"
      ANDROID_CMAKE:        "3.10.2.4988404"
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup java 8 for android sdk tools 
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'
      - name: Create Android emulator
        run: |
          yes | sudo ~/Library/Android/sdk/tools/bin/sdkmanager --licenses
          $ANDROID_HOME/tools/bin/sdkmanager --list
          $ANDROID_HOME/tools/bin/sdkmanager --install "system-images;android-31;google_apis;x86_64"
          echo "no" | $ANDROID_HOME/tools/bin/avdmanager --verbose create avd --force --name test --abi google_apis/x86_64 --package 'system-images;android-31;google_apis;x86_64'
      - name: Launch Emulator
        run: |
          $ANDROID_SDK_ROOT/emulator/emulator -avd test -gpu guest
      - name: setup java 11 for gradle
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Run test
        run: |
          ./gradlew connectedCheck --info